// Generated by CoffeeScript 1.4.0
(function() {

  (function(exports) {
    var Calendarn;
    Calendarn = (function() {

      function Calendarn(options) {
        this.options = options;
        this.startDate = this.formatDate(this.options.startDate);
        this.endDate = this.formatDate(this.options.endDate);
      }

      Calendarn.prototype.google = function() {
        var params;
        params = {
          action: 'TEMPLATE',
          text: this.options.title,
          details: this.options.description || '',
          location: this.options.location || ''
        };
        return "https://www.google.com/calendar/render?" + (this.parametrize(params)) + "&dates=" + this.startDate + "/" + this.endDate;
      };

      Calendarn.prototype.iCalendar = function() {
        return ["BEGIN:VCALENDAR", "VERSION:2.0", "BEGIN:VEVENT", "URL:" + (this.options.url || ''), "DTSTART:" + this.startDate, "DTEND:" + this.endDate, "SUMMARY:" + (this.options.title || ''), "DESCRIPTION:" + this.options.description, "LOCATION:" + (this.options.location || ''), "END:VEVENT", "END:VCALENDAR"].join('\n');
      };

      Calendarn.prototype.yahoo = function() {
        var params;
        params = {
          title: this.options.title,
          desc: this.options.description || '',
          in_loc: this.options.location || '',
          st: this.startDate.replace('Z', ''),
          et: this.endDate.replace('Z', '')
        };
        return "http://calendar.yahoo.com/?v=60&view=d&type=20&" + (this.parametrize(params));
      };

      Calendarn.prototype.formatDate = function(date) {
        if (!(date instanceof Date)) {
          date = new Date(date);
        }
        return date.toISOString().replace(/-|:|\.\d+/g, '');
      };

      Calendarn.prototype.parametrize = function(params) {
        var encoded, key, value;
        encoded = [];
        for (key in params) {
          value = params[key];
          encoded.push("" + (encodeURIComponent(key)) + "=" + (encodeURIComponent(value)));
        }
        return encoded.join('&').replace(/%20/g, '+');
      };

      return Calendarn;

    })();
    return exports.Calendarn = Calendarn;
  })(exports);

}).call(this);
